### ISSUE TITLE
Issue with latest antd package

### ISSUE THREAD

**Issue by andymills** [ChuckJonas/bad-ass-salesforce-stack#65]
I set up a project and on running npm run deploy-dev I received the following error: 

> rimraf dist

node_modules/antd/es/notification/PurePanel.d.ts:25:16 - error TS2304: Cannot find name 'PurePanel'.

25 export default PurePanel;
                  ~~~~~~~~~

Found 1 error in node_modules/antd/es/notification/PurePanel.d.ts:25

I forced the package to downgrade to 5.2.3 and the error went away. I think maybe the package needs to be fixed to this version until the issue with antd is resolved.

Andy

**Comment by andymills** [comment]
I went through all the packages and updated them all to the latest version and the above error went away. I must have messed something up the first time.

**Comment by ChuckJonas** [comment]
ya, it was probably just a bug in `antd@5.2.3`.  Packages are not "pinned" in this project, so that can happen occasionally (once `package-lock.json` is created with a good configuration, it shouldn't be an issue).
